# numpy 基础

In [2]:
import numpy

In [5]:
numpy.__version__

'1.14.3'

In [6]:
import numpy as np

# python list 特点

In [11]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
L[5]

5

In [13]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [15]:
L[8] = "machine learning"
L

[0, 1, 2, 3, 4, 100, 6, 7, 'machine learning', 9]

In [16]:
import array

In [18]:
arr = array.array("i",[i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array限制数组类型，list不限制，所以array计算速度会比list快

## numpy.array

In [20]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
nparr.dtype

dtype('int32')

In [22]:
nparr[5] = 5.0

In [23]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
nparr[3]=3.14

In [25]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

会自动对数据进行截位，自定义的数据类型与创建时输入的数据类型相关

In [26]:
nparr2 = np.array([1,2,3.14])

In [27]:
nparr2.dtype

dtype('float64')

# 其他创建numpy.array方法

In [28]:
numpy.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

0数组 默认浮点数

In [30]:
numpy.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

二维数组 记得双括号

In [33]:
np.zeros(shape=(2,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [35]:
np.full((2,2),666)

array([[666, 666],
       [666, 666]])

指定数值的数组，第二个值为指定数值,数据类型按照输入的指定数值的数据类型

In [36]:
np.full(shape=(2,2),fill_value=666)

array([[666, 666],
       [666, 666]])

In [38]:
np.full(fill_value=666,shape=(2,2))

array([[666, 666],
       [666, 666]])

## arange

In [39]:
[i for i in range(0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [40]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

[]不能传入浮点数。np.arange可以

## linspace

In [41]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

最后一个数值表示从0到20中截出10个等长的点 包括0和20

## random

In [42]:
np.random.randint(0,10)

0

In [43]:
np.random.randint(0,10,10)

array([6, 9, 0, 8, 8, 9, 1, 5, 8, 8])

注意取值区间是一个前闭后开的区间 上面的就取不到10

In [44]:
np.random.randint(0,10,size=10)

array([3, 3, 7, 6, 7, 0, 3, 3, 4, 1])

In [45]:
np.random.randint(0,10,size=(2,4))

array([[7, 2, 5, 0],
       [4, 6, 4, 9]])

对随机算法通用的调试技巧 随机种子

In [46]:
np.random.randint(0,10,size=(2,4))

array([[6, 0, 8, 1],
       [1, 2, 9, 6]])

In [47]:
np.random.seed(111)

In [48]:
np.random.seed(111)
np.random.randint(0,10,size=(2,4))

array([[4, 4, 4, 6],
       [3, 9, 2, 6]])

In [49]:
np.random.seed(111)
np.random.randint(0,10,size=(2,4))

array([[4, 4, 4, 6],
       [3, 9, 2, 6]])

In [50]:
np.random.random()

0.37786243967088273

默认生成浮点数

In [54]:
np.random.random(size=10)

array([0.2090237 , 0.64956403, 0.60170251, 0.71227309, 0.92044575,
       0.10403691, 0.52795781, 0.28181936, 0.64572137, 0.17804867])

生成的随机数默认在0-1之间 所以无法像整型一样设定范围

In [55]:
np.random.normal(size=10)

array([-0.79025422,  1.46369306, -1.30348505,  0.59474668,  1.4769256 ,
       -0.115229  ,  0.83970188,  0.47906574, -0.94404561,  0.92969174])

服从正态分布的浮点数，均值为0，方差为1

In [57]:
np.random.normal(10,100,size=10)

array([ -14.11296664,  146.60608496,  -92.83571366,  -68.91304206,
       -191.48268303,   76.17349105,  -75.37616573,  138.57793594,
         42.79105036, -174.86827866])

自定义均值（10）和方差（100）

random.seed 使用来存储随机数的

In [2]:
import numpy as np

In [3]:
np.random.seed(666)

In [4]:
np.random.randint(10,100,size=(2,5))

array([[12, 55, 40, 72, 80],
       [83, 40, 46, 71, 61]])

In [5]:
np.random.seed(666)
np.random.randint(10,100,size=(2,5))

array([[12, 55, 40, 72, 80],
       [83, 40, 46, 71, 61]])

In [6]:
np.random.randint(10,100,size=(2,5))

array([[70, 38, 24, 73, 26],
       [56, 49, 79, 92, 86]])

数组的合并和分割

In [7]:
A=np.random.randint(10,100,size=(2,4))
B=np.random.randint(1,10,size=(2,4))

In [8]:
A
B

array([[1, 1, 5, 1],
       [5, 6, 8, 2]])

In [9]:
A

array([[89, 23, 79, 30],
       [21, 34, 30, 46]])

In [11]:
np.concatenate([A,B])

array([[89, 23, 79, 30],
       [21, 34, 30, 46],
       [ 1,  1,  5,  1],
       [ 5,  6,  8,  2]])

In [12]:
np.concatenate([A,B],axis=1)

array([[89, 23, 79, 30,  1,  1,  5,  1],
       [21, 34, 30, 46,  5,  6,  8,  2]])

In [13]:
np.vstack([A,B])

array([[89, 23, 79, 30],
       [21, 34, 30, 46],
       [ 1,  1,  5,  1],
       [ 5,  6,  8,  2]])

In [15]:
np.hstack([A,B])

array([[89, 23, 79, 30,  1,  1,  5,  1],
       [21, 34, 30, 46,  5,  6,  8,  2]])

In [18]:
x=np.arange(16)

In [19]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])